### ISSUE TITLE
missing java-sample-demo sql script

### ISSUE THREAD

**Issue by Holyson** [dtm-labs/dtmcli-java#26]
CREATE TABLE `barrier` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `amount` int DEFAULT NULL,
  `trans_type` varchar(255) DEFAULT NULL,
  `gid` varchar(100) DEFAULT NULL,
  `branch_id` varchar(100) DEFAULT NULL,
  `op` varchar(255) DEFAULT NULL,
  `barrier_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `reason` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

**Comment by li-xiao-shuang** [comment]
> 

可以提个pr 补充下
