### ISSUE TITLE
tcc：get response.body().string() closed

### ISSUE THREAD

**Issue by Hibari8** [dtm-labs/dtmcli-java#39]
tcc模式下想要解析 response的body内容
但response.body().string()只能请求一次，在dtm内已经调用过此方法
请问是否还有其他解决方案可以获取返回值吗？

`    public static void checkResult(Response response) throws Exception {
        if (response.code() >= 400) {
            throw new FailureException(response.message());
        } else {
            ResponseBody body = response.body();
            String result;
            if (body != null && !StringUtils.isBlank(result = body.string())) {
                if (result.contains("FAILURE")) {
                    throw new FailureException("Service returned failed");
                }
            } else {
                throw new FailureException("response is null");
            }
        }
    }`

**Comment by horseLk** [comment]
问题已收到，后续会评估一下看是否做一个重载方法返回response的body
